name: puzzle_box
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^7.6.7

  flame: ^1.17.0
  flame_audio: ^2.10.4

  shared_preferences: ^2.3.2
  collection: ^1.18.0
  meta: ^1.13.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_game.png
    - assets/audio/
    - assets/animations/
    - assets/fonts/