name: puzzle_box
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Game Engine
  flame: ^1.17.0
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Audio
  audioplayers: ^5.2.1
  
  # UI & Animations
  flutter_animate: ^4.5.0
  rive: ^0.12.4
  
  # Utilities
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  uuid: ^4.2.1
  
  # Development
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/animations/
    - assets/fonts/